add icon
ChubachiPT2024/manakan pull request #175
Opened 2024-07-17 02:38 UTC by tadashimasuda

2024-07-17 06:12 UTC, shunya9811 reviewed
良いアイコンですね！！

2024-07-17 06:12 UTC, shunya9811 approved these changes

2024-07-17 16:44 UTC, shunya9811 commented on src/presentation/pages/Classification.tsx
ここの削除は意図したものですか？

2024-07-17 16:44 UTC, shunya9811 commented on package-lock.json
ここの変更も同様で必要な変更ですか？

2024-07-17 16:46 UTC, shunya9811 requested changes
アイコン以外の修正は必要ない気がしていますが、どうでしょうか？

2024-07-19 04:05 UTC, shunya9811 commented on src/presentation/pages/Classification.tsx
> -    const selectedSubmissions = report.items.filter((item) => item.isChecked)
この削除は意図したものですか？

2024-07-19 07:40 UTC, a2307yo commented
このPRで追加されたアイコンをもとに
Windows用のデスクトップアイコンを追加しました
#191

2024-07-19 15:30 UTC, shunya9811 approved these changes

2024-07-20 04:38 UTC, merged