分類ページでのコース名表示
ChubachiPT2024/manakan pull request #188
Opened 2024-07-18 16:11 UTC by a2307yo

#174
変更内容
・コース名、レポート名の読み込み追加
・コース名、レポート名のスタイル調整

確認内容
・分類ページにコース名とレポート名が表示されていることを確認
・コース名とレポート名のフォントサイズ、位置が他の要素に重ならないことを確認

懸念事項
#181 のPRで実装されたuseReportCourseを使って実装したほうが良いかも

2024-07-18 16:17 UTC, shunya9811 commented
src/application/reportLists/reportListData.ts
```
export class ReportListData {
  /**
   * コンストラクタ
   *
   * @param courseId コース ID
   * @param courseName コース名
   * @param reportId レポート ID
   * @param reportTitle レポートタイトル
   * @param items レポートリスト項目
   */
  public constructor(
    public readonly courseId: number,
    public readonly courseName: string,
    public readonly reportId: number,
    public readonly reportTitle: string,
    public readonly items: ReportListItemData[]
  ) {}
}
```
にあるように、既存で使っているgetReportAsyncを使用すれば、コース名は取得できるはずです。
reportCourseDataは使わないはずです

2024-07-18 16:18 UTC, shunya9811 requested changes
src/application/reportLists/reportListData.ts
```
export class ReportListData {
  /**
   * コンストラクタ
   *
   * @param courseId コース ID
   * @param courseName コース名
   * @param reportId レポート ID
   * @param reportTitle レポートタイトル
   * @param items レポートリスト項目
   */
  public constructor(
    public readonly courseId: number,
    public readonly courseName: string,
    public readonly reportId: number,
    public readonly reportTitle: string,
    public readonly items: ReportListItemData[]
  ) {}
}
```
にあるように、既存で使っているgetReportAsyncを使用すれば、コース名は取得できるはずです。
reportCourseDataは使わないはずです

2024-07-18 16:41 UTC, a2307yo commented
> src/application/reportLists/reportListData.ts
> 
> ```
> export class ReportListData {
>   /**
>    * コンストラクタ
>    *
>    * @param courseId コース ID
>    * @param courseName コース名
>    * @param reportId レポート ID
>    * @param reportTitle レポートタイトル
>    * @param items レポートリスト項目
>    */
>   public constructor(
>     public readonly courseId: number,
>     public readonly courseName: string,
>     public readonly reportId: number,
>     public readonly reportTitle: string,
>     public readonly items: ReportListItemData[]
>   ) {}
> }
> ```
> 
> にあるように、既存で使っているgetReportAsyncを使用すれば、コース名は取得できるはずです。 reportCourseDataは使わなくも、もっと簡単にできると思いますよ！！

ご指摘いただきました内容を確認し、修正しました！！
少しパッチワーク的な修正となりましたが、大本から修正すると影響が大きそうなため、コース名の取得のみを純粋に追加しました。

2024-07-18 16:48 UTC, shunya9811 approved these changes
対応ありがとうございます！！まさにこれだけの作業だと思っていたので、自分が並行してreportCourseDataの方をやっていたから混乱させてしまったかもしれません。

2024-07-19 02:39 UTC, tadashimasuda approved these changes

2024-07-19 06:06 UTC, merged